name: NASA Project Ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: ls -l
      - name: Install Dependencies
        run: npm install
      - name: Build Project
        run: npm run build --prefix client
        env:
        CI: true
        shell: bash -eux
