name: NASA Project Ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Install plugin
        run: npm install --save-dev @babel/plugin-proposal-private-property-in-object --legacy-peer-deps
      - name: BUILD
        run: npm run build --prefix client
