name: NASA Project Ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  jobs:
    # con needs vincoliamo il deploy alla fase di build,quindi in caso di errori in fase di build il deploy non verrà effettuato
    build:
      runs-on: ubuntu-lastest
      # dove definiamo le azioni che verranno eseguite su ubuntu
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: "16"
        # possiamo anche eseguire dei comandi utilizzando il sistema operativo indicato
        - run: npm install
        - run: npm run build --prefix client
    deploy:
      needs: build
